#!/usr/bin/env python3
# Generated by less_tokens. Codex compatibility shim.
from __future__ import annotations

import os
import runpy
import sys
from pathlib import Path

os.environ.setdefault("LESS_TOKENS_AGENT", "codex")
BASE = Path(__file__).resolve().parents[2]
REAL = BASE / ".claude" / "tools" / 'search.py'
if not REAL.exists():
    raise SystemExit(f"less_tokens shim target missing: {REAL}")
sys.path.insert(0, str(REAL.parent))

if __name__ == "__main__":
    runpy.run_path(str(REAL), run_name="__main__")
else:
    _data = runpy.run_path(str(REAL), run_name=f"_less_tokens_real_{REAL.stem}")
    for _key, _value in _data.items():
        if _key not in {"__name__", "__file__", "__cached__", "__loader__", "__package__", "__spec__"}:
            globals()[_key] = _value
